<?php

/***************************************************************************
      This file was automatically generated by Admin FAQ Editor
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
 
$faq[] = array("--", "Acerca del ingreso (login) y registro");
$faq[] = array("¿Por qué no puedo ingresar?", "¿Ya estás registrado? Debes registrarte en Rock Republik antes de poder acceder a todas las opciones. ¿Has sido bloquedado? (si es así un mensaje aparecerá). Si esto sucede envíale un mensaje a un Administrador para encontrar la causa. Si te has registrado y no ha sido bloquedado verifica que tu nombre de usuario y contraseña coincidan, es el problema mas común. Si estás seguro de que están correctos los datos, envia un mensaje un Administrador.");
$faq[] = array("¿Por qué me tengo que registrar para todo?", "No estas obligado a hacerlo, pero no podrás accesar todas las caraterísticas de Rock Republik. Sin embargo estar registrado te da muchas ventajas que un usuario invitado no difrutaría, como tener tu gráfico personalizado (Avatar), mensajes privados, suscripcion a grupos de usuarios, chat privado, descarga de música, etc. Solo te tomará unos segundos, es muy recomendable.");
$faq[] = array("¿Por qué mi sesión de usuario expira automaticamente?", "Si no activas la casilla <i>Ingresar automáticamente</i> cuando ingresas a Rock Republik, tus datos se guardan en una cookie que se elimina al salir de la página o en cierto tiempo. Esto previene que tu cuenta pueda ser usada por alguien más. Para que el sistema te reconozca automáticamente solo activa la casilla al ingresar. NO es recomendable si accesas a Rock Republik desde una computadora compartida (café-internet, colegio, etc.)");
$faq[] = array("¿Como evito aparecer en las listas de usuarios conectados?", "En tu perfil, encontrarás la opción <i>Ocultar mi estado de conexión</i>, si activa esta opción aparecerás solo para los Administradores, Moderadores, para tus amigos y para ti mismo, para los demás serás un usuario oculto.");
$faq[] = array("¡He perdido mi contraseña!", "Calma, si tu contraseña no puede ser recuperada puedes desactivarla o cambiarla. Para hacer esto dirigete a la página de registro y haz click en <u>Olvidé mi contraseña</u>, sigue las instrucciones y estará listo dentro en muy poco tiempo");
$faq[] = array("¡Me he registrado y no puedo ingresar!", "Primero verifica tus datos (usuario y contraseña). Si todo es correcto, contacta a un Administrador de Rock Republik.");
$faq[] = array("Hace un tiempo me registré, pero ahora no puedo ingresar", "Las posibles razones son: has ingresado un nombre de usuario o contraseña incorrectos (verifica el mensaje que se te envia al registrarte). Es posible que el Administrador haya borrado tu cuenta, esto es muy frecuente, pues si no has escrito ningun mensaje en cierto tiempo un Administrador puede borrar tu usuario para no saturar el sistema de registros. Si es así, registrate de nuevo y participa :)");

$faq[] = array("--", "Preferencias de usuario y configuración");
$faq[] = array("¿Cómo puedo cambiar mi configuración?", "Todos tus datos y configuraciones están guardados en nuestro sistema. Para modificarlos dirígete al menu <u><b>Tu Perfil</b></u>, que se encuentra arriba de cada página.");
$faq[] = array("La hora en Rock Republik no es correcta!", "Las horas son corectas, es posible que estés viendo las horas correspondientes a otra zona horaria, si este es el caso, ingresa a tu perfil y define tu zona horaria de acuerdo a tu ubicación (para Guatemala es: GMT -6). Cambiando esto las horas deben aparecer de acuerdo a tu zona y tiempo.");
$faq[] = array("He cambiado la zona horaria en mi perfil, pero el tiempo sigue siendo incorrecto", "Si estas seguro que la zona horaria es correcta es posible que se deba a los horarios de verano implementados por algunos paises.");
$faq[] = array("Cómo puedo poner una imagen abajo de mi nombre de usuario?", "Hay dos tipos de imágenes debajo de tu nombre de usuario, la primera es el <b>Rango</b>, que está asociada con el número de mensajes que has escrito en el foro, la segunda es el <b>Avatar</b>, que es un gráfico generalmente único y personal, puedes introducirlo en tu perfil.");
$faq[] = array("¿Como puedo cambiar mi Rango?", "No puedes cambiar tu Rango directamente, ya que éste es asociado directamente con el número de mensajes publicados.");
$faq[] = array("Cuando doy click sobre el link de e-mail me pide que me registre", "Para poder enviar e-mail a un usuario via formulario necesitas registrarte, esto para evitar SPAM o mensajes maliciosos de usuarios anónimos.");
$faq[] = array("¿Cómo puedo seleccionar a mis amigos?", "Entra a la lista de miembros y dá click sobre algún usuario, y verás su perfil, en el cuál aparece un botón llamado <i>Amigo</i>, presionalo y así habrás hecho a ese usuario tu amigo. Repite este procedimiento para todos usuarios que desees.");

$faq[] = array("--", "Publicación de mensajes");
$faq[] = array("¿Como puedo publicar un mensaje en el foro?", "Fácil, registrate como miembro de Rock Republik, después del registro puedes ir al foro y presiona sobre <b>Enviar nuevo mensaje</b>, ahí se te presentará un panel con el que facilmente publicarás un mensaje :)");
$faq[] = array("¿Como puedo agregar una firma a mi mensaje?", "Para insertar una firma en tu mensaje primero debes crear una, esto se hace modificando tu perfil. Una vez creada activas la opción <i>Agregar firma</i> cuando publiques un mensaje. También puedes hacer que todos tus mensajes tengan tu firma, activando la opción en tu perfil.");
$faq[] = array("¿Cómo creo una encuesta?", "Crear una encuesta es fácil, cuando inicias un nuevo tema notarás la opción <i>Crear una encuesta</i>, introduces los datos de la encuesta, como titulo y opciones, tienes la posibilidad de poner fecha de expiración para la encuesta (0 es infinito)");
$faq[] = array("¿Por qué no puedo accesar a algún foro?", "Algunos foros están limitados a ciertos grupos de usuarios, para verlos, publicar, etc, necesitas tener una autorización, la cuál solo te puede dar un Administrador del foro.");
$faq[] = array("¿Por qué no puedo votar en las encuestas?", "Solo miembros registrados pueden votar en las encuestas (para prevenir resultados trucados), si te has registrado pero no puedes votar, es posible que no tengas autorización para votar en esa encuesta :(.");

$faq[] = array("--", "Formateo de mensajes y tipos de temas");
$faq[] = array("¿Qué es el código BBCode?", "BBCode es una implementación especial, es muy similar al HTML, las etiquetas van entre corchetes [ y ] para mas información puedes ver el manual de BBCode, el enlace aparece cada vez que publicas un mensaje.");
$faq[] = array("¿Qué son los Smilies?", "Smilies o Emotíconos son pequeños gráficos que pueden ser usados para expresar emociones, aparecen introduciendo un pequeño código, por ejemplo:  :) significa feliz, :( significa triste. La lista completa de smilies se despliega cuando envias un mensaje.");
$faq[] = array("¿Puedo publicar imágenes?", "Las imagenes pueden ser adheridas al mensaje, insertandolas al momento de redactarlo. No puede haber imágenes de sitios de correo, busqueda o cualquier autentificacion (Yahoo, Hotmail, Google, etc.).");
$faq[] = array("¿Qué son los anuncios?", "Los anuncios contienen información importante para los usuarios.");
$faq[] = array("¿Qué son los Temas Importantes?", "Los Temas Importantes aparecen debajo de los anuncios y solo en la primera página, es información muy importante que deberías leer :)");
$faq[] = array("¿Qué son los temas cerrados o bloquedados?", "Son temas en los que no se puede publicar más mensajes.");

$faq[] = array("--", "Niveles de usuario y grupos");
$faq[] = array("¿Qué son los Administradores?", "Los Administradores son personas asignadas con alto nivel de control sobre Rock Republik NET completo, pueden controlar permisos, moderadores y cualquier configuración.");
$faq[] = array("¿Qué son los Moderadores?", "Moderadores son personas que tienen el poder de editar o borrar foros, cerrarlos o abrirlos. Son designados por un Administrador y tienen menos opciones que este. Los Corresponsales de Rock Republik también son Moderadores.");
$faq[] = array("¿Qué son los grupos de usuarios?", "Los Grupos de Usuarios es una de las formas para agrupar usuarios. Un usuario puede pertenecer a varios grupos. Esto se hace con el fin de conceder permisos selectivos sobre Rock Republik.");
$faq[] = array("¿Cómo puedo pertenecer a un Grupo de Usuarios?", "Dá click en Grupos de usuarios y pide tu inscripcion, recibiras un mail si eres aceptado.");

$faq[] = array("--", "Mensajería privada");
$faq[] = array("No puedo enviar mensajes privados!", "Hay dos posibles razones: No estas registrado o no has ingresado, o un Administrador ha deshabilitado la mensajería para ti.");
$faq[] = array("Quiero evitar mensajes privados no deseados!", "En tu perfil, puedes seleccionar recibir únicamente mensajes privados de tus amigos, o puedes bloquear definitivamente todos los mensajes privados. Si tienes cualquier consulta o reclamo, pro favor contacta a un Administrador.");
$faq[] = array("He recibido spam o correos amaliciosos de alguien de Rock Republik", "Lo sentimos mucho, la caracteristica de enviarr emails tiene amplios conceptos de seguridad y privacidad. Envia el mail un Administrador, tal como venía, incluyendo headers y demas, el tomará las acciones necesarias.");

$faq[] = array("--", "Acerca de phpBB2");
$faq[] = array("¿Quien programó este foro?", "Esta aplicación (en su forma original) es producida, liberada y con derechos de autor pertenecientes al <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>. Está hecho bajo la GNU (Licencia Pública General) y es de libre distribución (click en el enlace para conocer mas detalles)");

?>