<!-- INCLUDE js/upload/jquery.ui.widget.js -->
<!-- INCLUDE js/upload/load-image.min.js -->
<!-- INCLUDE js/upload/canvas-to-blob.min.js -->
<!-- INCLUDE js/upload/jquery.iframe-transport.js -->
<!-- INCLUDE js/upload/jquery.fileupload.js -->
<!-- INCLUDE js/upload/jquery.fileupload-process.js -->
<!-- INCLUDE js/upload/jquery.fileupload-image.js -->
<!-- INCLUDE js/upload/jquery.fileupload-audio.js -->
<!-- INCLUDE js/upload/jquery.fileupload-video.js -->
<!-- INCLUDE js/upload/jquery.fileupload-validate.js -->